name: tf2
channels:
  - defaults
  - conda-forge/label/broken
dependencies:
  - pandas-profiling
  - networkx
  - seaborn
  - folium
  - plotly
  - scikit-learn
  - pandas
  - tensorflow
